export const ACTION_ADD_MEMBER = 'ACTION_ADD_MEMBER'
export const ACTION_ADD_MEMBER_REQUEST = 'ACTION_ADD_MEMBER_REQUEST'

export const ACTION_REMOVE_MEMBER = 'ACTION_REMOVE_MEMBER'
export const ACTION_REMOVE_MEMBER_REQUEST = 'ACTION_REMOVE_MEMBER_REQUEST'

export const ACTION_EDIT_MEMBER = 'ACTION_EDIT_MEMBER'
export const ACTION_EDIT_MEMBER_REQUEST = 'ACTION_EDIT_MEMBER_REQUEST'
